### ISSUE TITLE
Use $XDG_CONFIG_HOME instead of $HOME/.config for $CONFDIR when available

### ISSUE THREAD

**Issue by grayk-79** [ControlxFreak/go2#11]
I personally don't use .config for my config data and the script doesn't respect that.

**Comment by ControlxFreak** [comment]
Oh wow I've never heard of that.  Sorry about that!  I will make that change.

**Comment by ControlxFreak** [comment]
I believe I fixed it in commit a45fec9, let me know if you have any issues.
