### ISSUE TITLE
Add go2 to the Arch Linux AUR

### ISSUE THREAD

**Issue by ControlxFreak** [ControlxFreak/go2#3]
I don't know how to do this yet, maybe someone in the community can help! :)

Future work would also be to add this to other Linux package repos like debian's apt.

**Comment by giacomogallina** [comment]
By the way, the PKGBUILD still doesn't contain the mantainer name and email, so you might want to add them

**Comment by ControlxFreak** [comment]
Thanks to your help it is on the AUR now! :)
