### ISSUE TITLE
`#!/bin/bash` should be first line

### ISSUE THREAD

**Issue by Hades0299** [ControlxFreak/go2#8]
Hi, AFAIK the linw with `#!/bin/bash` should be in the firtst line of the scripts.

This might also fix #5.

Regards
Hades

**Comment by ControlxFreak** [comment]
Ahhhh good catch.  Thanks!  I'll make that change.

**Comment by ControlxFreak** [comment]
Fixed this in commit a45fec9.  I did not see it fix issue #5 but I'm going to keep testing it and poking around to see whats up.

Out of curriousity, why do you think this would fix #5?

**Comment by Hades0299** [comment]
The line `#!/bin/bash` tells the shell, to run this programm as `/bin/bash go2` (as an example), or in other words in a new Process. So there should be no variables left in the current shell, as they are created in another bash in another Process.

**Comment by ControlxFreak** [comment]
Yeah but unfortunately the intention of the 'alias go2=. go2' is so go2 _does_ execute in the current shell (otherwise cd would be pointless - it would cd a bash shell in another process and then terminate).

**Comment by Hades0299** [comment]
Looks like I didn't think before writing ;)
